travis:
  secure:
    BINSTAR_TOKEN: ci7eK3T8nTSTPbfT5fnsPT/vWeOviEs2tCCcFsLVInuVVRHK6T+RCH/7wrNd+8Da+m3cPPv4C75krxMXdkcBwCE8pwUC4eaPUbt6CV3HotwcglMSvBcOdH+fOQyK2broVI7JDOkvJw1xOnMNmSH1cb6m4vUDIx5nmaqiv/X+Ie85Fs6aLacapaJNHB4pEqa0W8FfTzXOOzQFhTPKMaPG0rTRniF9+Ws8eAX7ZuzuV6cdQnBgQRI+EA5Vhi9cUZCPzfeb9idenfpvnF5nNimT0VIJg0fKut3DhVOovJuKhMIWCQqUIX9Xv9nE7hrCFc4E7Y/Ppd+JPlZ+KhAMYuwi3b3usY5wXEAbZ/72QpKdh5GrYQgnLWbtdlI7DpY2WED+GZC+sZ4mdsm5suPQsOvjGA+I8IDUJnT6GkXyz3z1lFBY7wRMjaYKypSPP+8ioU0QmufyX3U7lSBrxFVa46+VBCKEnQmsFSIlHJfoQBbimY//CLNVOaEqc2P7opZwA5VhbDTSASehJdjtY/YL7lirWaNaupFMjSe7c7Xl8PSpMfJp7P1HdKYFNQPLWwDpcScwo61hXKBG0k31snzFYasvybrtQTLYKtofGmDHLOJy862fxW5vk9Ap0SyYdeE4xbR9x9xQ3OSGBv2g/QGT9QU/xUkeozs77GWl8IsKl8G7CpE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
