travis:
  secure:
    BINSTAR_TOKEN: JqwBOkp0kTs2MQM1i44PbVn4fSpjgi8cLBAqIL6AxK4mk1tdtueAjFCf1TsjHdbNg712DKAcOPObvKGGzA4XrQVI0Em23eMascHD3emhlMvEROdJmBlmWgZwH64LJxXnUuTgbAgyNZmXaQ0YzbYjAi5j2+/PLia1TSxVJW6UOqYEZ8eZwJ+hdrormwdkSD5DVKIPRAXL2wv94rBwKDyI/2cPAFxWeLRA/w4/zoEYFYBIJvtnac/Gtp8ns6LjdnG/7raVicYZMalfsLsxdw+cVdil4jLAF1mTK+ruT4x/XbWlCuimzvn8B5d6X8uwUOce5Z9xyjz75XiA6N3O6nalEpwylEfKxDSScspwDj6Oa+EAhYogKYd37cgVdWer8/CXc6IW7QxkeZMOYhuLXR/Cx3tUdt0u5B8dagP8Lew3u+YJOKUDtOofTgi5/DjKtqgS+eY1tPjApkZhNji8In6dtr2VuoojnZduDWZ/Aahgsn1wd1N2h4pj6EQLmZPIHLx+02+XIuqZbcZRD7KaXt6jDaTepAgRTR1UjYZC/dY2ccxnBHLSPCFPMjrLtUmYXwWS2zmYjo9HItEgaJOkNiruR5purc0DeuRBTp1rAGq5MSlIJgbzcM81sZ2zdA2DJ3Cz1HZjT1ghOO9E+4ltkKqbdxx5A7Na5WxQrgAAKk+/eK8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
